### ISSUE TITLE
Error in the sample

### ISSUE THREAD

**Issue by daviddelamo** [galkahana/HummusJSSamples#6]
Hello, trying to reproduce the fill form sample with exactly the same code I'm having this error:

ReferenceError: modifiedAcroFormDict is not defined
    at writeFieldAndKids (G:\DAMA\hitoscreator\public\controller\pdf-form-fill.js:366:9)
    at writeFilledField (G:\DAMA\hitoscreator\public\controller\pdf-form-fill.js:392:9)
    at G:\DAMA\hitoscreator\public\controller\pdf-form-fill.js:436:13
    at Array.forEach (native)
    at writeFilledFields (G:\DAMA\hitoscreator\public\controller\pdf-form-fill.js:433:22)
    at writeFilledForm (G:\DAMA\hitoscreator\public\controller\pdf-form-fill.js:458:9)
    at fillForm (G:\DAMA\hitoscreator\public\controller\pdf-form-fill.js:500:9)
    at generatePDF (G:\DAMA\hitoscreator\public\controller\pdf.js:15:3)
    at Layer.handle [as handle_request] (G:\DAMA\hitoscreator\node_modules\express\lib\router\layer.js:95:5)
    at next (G:\DAMA\hitoscreator\node_modules\express\lib\router\route.js:137:13)

The PDF that I'm trying to modify is version 1.4. Any tip on how to resolve this problem?

PD: Excuse my poor english :(

**Comment by daviddelamo** [comment]
The error only occurs with my PDF template, using the one with the sample everything works.

**Comment by galkahana** [comment]
Wanna send the example for inspection?

**Comment by mshrfrkw** [comment]
Hello. I'm having the same error.
>ReferenceError: modifiedAcroFormDict is not defined
    at writeFieldAndKids (/home/vcap/app/pdf-form-fill.js:366:9)
    at /home/vcap/app/pdf-form-fill.js:436:13
    at Array.forEach (native)
    at writeFilledFields (/home/vcap/app/pdf-form-fill.js:433:22)
    at writeFilledForm (/home/vcap/app/pdf-form-fill.js:458:9)
    at fillForm (/home/vcap/app/pdf-form-fill.js:500:9)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vcap/app/node_modules/express/lib/router/route.js:131:13)

I call fillForm function as below.
```
var hummus = require('hummus'),
	fillForm = require('./pdf-form-fill').fillForm;

    var writer = hummus.createWriterToModify(__dirname + '/public/create-forms-sample.pdf', {
			modifiedFilePath: __dirname + '/public/create-forms-sample-out.pdf'
		});

    var data = {
        "Field Office Location": "Tokyo"
    };

    fillForm(writer,data);
    writer.end();
```

I'm using input pdf that was downloaded from
http://wwwimages.adobe.com/content/dam/Adobe/en/feature-details/acrobat/axi/pdfs/create-forms-sample.pdf

It's linked from following URL
https://acrobat.adobe.com/jp/ja/acrobat/how-to/create-fillable-pdf-forms-creator.html

**Comment by galkahana** [comment]
Thanks. had some bugs with multi-level forms. fixed.
note that the field name is "location" (per the T key) and not "Field Office Location".

**Comment by mshrfrkw** [comment]
Thank you. It works!
